name: 'Wallpaper Update'

on:
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Set up Python'
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: 'Install dependencies'
        run: if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: 'run update-wallpaper.py'
        run: python update-wallpaper.py
      - name: Commit now.jpg
        run: |
          git config --global user.name 'lyz05'
          git config --global user.email '294068487@qq.com'
          chmod +x ./update-repo.sh&&./update-repo.sh